services:
  villarent.api:
    image: villarent.api
    container_name : villarent.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: VillaRent.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      villarent.database:
        condition: service_healthy
      villarent.cache:
        condition: service_started
          
#  villarent.web:
#    image: villarent.web
#    container_name: villarent.web
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Production
#    build:
#      context: .
#      dockerfile: VillaRent.Web/Dockerfile
#    ports:
#      - "8082:8082"
#      - "8083:8083"
      
  villarent.database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: villarent.database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test: "exit 0"

  
  villarent.cache:
    image: redis:latest
    container_name: villarent.cache
    restart: always
    ports:
      - '6379:6379'