services:
  villarent.api:
    image: passyexe/villarent.api:v1.2
    container_name : villarent.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      villarent.database:
        condition: service_healthy
      villarent.cache:
        condition: service_started
      
  villarent.database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: villarent.database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test: "exit 0"

  
  villarent.cache:
    image: redis:latest
    container_name: villarent.cache
    restart: always
    ports:
      - '6379:6379'